common/sessionhandler.py
common/urlinitialization.py

Addressing https://github.com/redhat-eets/glpi-helper-scripts/issues/17

Adding timouts for urllib.request.urlopen and error for wrong token

---

common/sessionhandler.py

Add error message when the REST session doesn't initialize.
Before:
```
session_token.json()['session_token']})
TypeError: list indices must be integers or slices, not str
```
After:
```
An error occurred when initializing the REST session:
['ERROR', 'API Disabled']
exiting...
```

Add more verbose error message for missing session token

---

common/urlinitialization.py
filtering/filter_computers.py

Adding links to print statement to better view reservable computers 
Adding Available field to print to show all available machines 
Improving usablility of progress indicator
Speeding up time of filter, short circuiting non-reservable computers to approximately half the execution time (further improvements definitely exist)
Partially addressing https://github.com/redhat-eets/glpi-helper-scripts/issues/16
real	0m39.507s
user	0m4.582s
sys	0m0.070s

Refactor of filter_computers:

---

integration/sunbird/compare_sunbird_with_glpi.py

There are some entries that don't have serial numbers that were breaking the script. So these changes filter those entries out.
Also change the comparison with GLPI to match regardless of the serial number's case, eliminating ~25 false positives

Make sure that we only pull machines from sunbird that have serial numbers

---

reservation/create_glpi_reservation_wrapper.py
reservation/reservation_example.yaml

This PR reworks the `reservation/create_glpi_reservation_wrapper.py` script to make the JIRA epic optional, like `create_glpi_reservation.py`. This is accomplished by making sure that the YAML isn't "indexed" on the JIRA epic, and by treating the `epic` attribute like the other attributes, such as `username`

make epic optional in yaml and wrapper script

---

common/utils.py
population/create_glpi_computer.py
population/create_glpi_computer_redfish.py
reservation/create_glpi_reservation.py

This PR refactors code from `check_and_post_x()` functions to avoid repeating code:
- `check_field()` modified so that it can compare user-defined fields
- All existing calls to `check_field()` updated to use new definition
- `create_or_update_glpi_item()` added to remove repeated logic that sends a POST request if the item doesn't already exist in GLPI.
- Introduces small regression: Rack locations will no longer be updated dynamically. But this is something that should be added to other items, so it would've been good to come up with a more general solution anyways.
This will hopefully make things like writing tests easier. Now that a lot of repeated code has been refactored, the next step is to combine as many `check_and_post_x()` functions as possible.

Reorganize check_and_post functions

---

common/utils.py
population/create_glpi_computer.py
population/create_glpi_computer_coreos.py
population/create_glpi_computer_redfish.py
population/create_glpi_computer_redfish_wrapper.py
population/update_switch_ports.py
tests/common/test_utils.py

- Combine similar functions (`check_and_post_x()` into one common function `check_and_post()`, reducing duplicated logic and making it easier to write tests/maintain
- Update existing calls to `check_and_post()` to use new syntax
- Some functions, such as `check_and_post_nic()`, `check_and_post_network_port_ethernet()`, and `check_and_post_network_port()` had existing logic that I broke out of the function in order to use the common function. There shouldn't be any regressions from this change, since that logic is still called.
- Remove functions and their corresponding imports/tests

Combine check and post

---

common/utils.py
filtering/check_glpi_computers.py
filtering/filter_computers.py
filtering/filter_reservations_by_project.py
integration/ldap/compare_ldap_with_glpi.py
integration/sunbird/compare_sunbird_with_glpi.py
population/create_glpi_computer.py
population/create_glpi_computer_coreos.py
population/create_glpi_computer_redfish.py
population/update_switch_ports.py
tests/common/test_utils.py

Previously, `check_fields()` returned a list of lists, each of which contained a response object. This meant that every time `check_fields()` was called, the list it returned had to be converted and "flattened" so that it would be a list of dictionaries.
This PR modifies check_fields() so that it returns the desired list. Now we can iterate over the return value using
```
for glpi_field in glpi_fields_list:
```
instead of 
```
for glpi_fields in glpi_fields_list:
for glpi_field in glpi_fields.json()
```
and `get_computers()`, `get_disks()`, `get_network_equipment()`, and `get_all_users()` can be removed.

Simplify check_fields()

---

common/format_dicts.py

When writing tests for format_dicts.py, I spotted some potential errors:
- Remove unused arguments and comments, and rename variables
- I believe `strip_brctl_showmacs_switch_dict()` is checking the wrong index for "no". Given the output for the brctl command: 
```
port no mac addr                is local?       ageing timer
1     00:11:22:33:44:55       no             0.00
2     66:77:88:99:AA:BB       yes            0.00
3     CC:DD:EE:FF:00:11       no             15.29
```
I believe it should check index 2, rather than 3, since is local? is the third entry on each line. I tested it on a VM, but I wasn't able to replicate the lab environment. Let me know if you think I have this wrong

Fix issues with format dicts

---

population/create_glpi_computer_redfish.py

Helps with #66 
- Use .dict in get_memory()
- Also remove json.loads() in post_to_glpi(), since it's no longer necessary (we're passing in a dict instead of json now)
- fix bug in get_network()
- use .dict for system_summary

Convert get_memory() to use .dict instead of .text

---

population/create_glpi_computer_redfish.py

If "NetworkPorts" is not in the redfish response, we should skip the next section of code where it is used to avoid an error.

Handle cases where "NetworkPorts" does not exist in the redfish response

---

integration/ldap/compare_ldap_with_glpi.py
population/create_glpi_computer_redfish.py

The pyYaml package can read yaml content from strings. This PR adds the ability to read yaml's defined as env var's for use in our cron jobs

Add ability to read ldap groups from env vars

---

population/create_glpi_computer_redfish.py

We have some machines that time out when trying to logout from the redfish session. This PR reverts back to our previous behaviors, and handles problematic logouts.

Revert context manager to better handle logout

---

integration/ldap/compare_ldap_with_glpi.py
integration/ldap/general_ldap_example.yaml

There are cases where we want multiple ldap groups to be assigned to a GLPI group. This PR updates the script to accommodate these changes

Multiple ldap groups

---

README.md
filtering/check_glpi_reservation.py
reservation/create_glpi_reservation.py
reservation/reservation_example.yaml

Addressing #96 
This seems like a holdover from the on-computer population script which would default to only using the hostname as an identifier. Since it is now more likely to be a serial number or service tag, this should be changed in documentation. There was already one user who brought this up as a point of confusion given most systems do not have hostnames in the GLPI instance

Swap references to hostname for server to identifer in reservation scripts

---

population/create_glpi_computer_redfish.py

This will protect us from overwriting machines that coincidentally have the same serial number. For example, if multiple machines have blank serial numbers, they will not be imported as unique items, and will instead overwrite each other. This PR prevents this by checking if the computer already exists by using both serial number and uuid.

check for duplicates based on serial AND uuid

---

.github/workflows/lint.yaml
requirements-dev.txt
requirements.txt

Resolves #67 - now users of the scripts don't have to install pytest, flake8, etc.

add requirements-dev.txt

---

filtering/filter_computers.py

Use `get_reservations()` from `utils.py` directly, rather than using subprocess, which calls a script that eventually runs the same function. Helps with #65

Remove subprocess from filtering script

---

population/create_glpi_computer_redfish.py

Sometimes when logging out from Redfish, a machine will throw a `BadRequestError`. This PR handles such cases.

Handle bad redfish logout request

---

population/create_glpi_computer_redfish.py

We already gather `computer_model_id`, there's no need to re-gather it from GLPI API.

use pre-existing computer_model_id

---

common/utils.py

Errors commonly occur when attempting a post request in `check_and_post()`. This PR adds some more verbose messaging to help debug.

Print cause of common error

---

population/create_glpi_computer_redfish.py

Some machines have GPU's registered as RAM, avoid importing these assets as RAM

filter out ram entries with GPU in title

---

utilities/count_tags.py

This script counts the number of tags on machines. Helps us determine if groups have removed their tags as expected.

Add script to count tags

---

common/utils.py
integration/ldap/compare_ldap_with_glpi.py
integration/sunbird/compare_sunbird_with_glpi.py
integration/sunbird/example_sunbird.yml

Generalize YAML parsing function so that more scripts can be used in our OpenShift cronjobs. Now, we can feed configs in via ConfigMap env vars in addition to yaml/json files.

Generalize yaml parsing

---

population/create_glpi_computer_redfish.py

SpeedMbps may exist as a key but be None, GLPI won't accept a Null/None Speed.
Attempting to update an existing computer in GLPI, resulted in a traceback with `Couldn't post item because of: ['ERROR_GLPI_ADD', "Column 'speed' cannot be null"]` Looking at the output of networks_dict showed several interfaces whose speed was None
```
{'@odata.context': '/redfish/v1/$metadata#EthernetInterface.EthernetInterface', '@odata.etag': 'W/"F9E3F527"', '@odata.id': '/redfish/v1/Systems/1/EthernetInterfaces/13', '@odata.type': '#EthernetInterface.v1_4_1.EthernetInterface', 'Id': '13', 'FullDuplex': False, 'IPv4Addresses': [], 'IPv4StaticAddresses': [], 'IPv6AddressPolicyTable': [], 'IPv6Addresses': [], 'IPv6StaticAddresses': [], 'IPv6StaticDefaultGateways': [], 'InterfaceEnabled': None, 'LinkStatus': …
```

handle None for interface speeds
