redhat-eets/glpi-helper-scripts

.github/workflows/lint.yaml

Adding a GitHub action to ensure that code passes a linter before being merged.

Adding GitHub lint workflow

---

common/format_dicts.py
common/sessionhandler.py
common/switches.py
common/urlinitialization.py
common/utils.py

Formatting dicts
SessionHandler Class
Switches Class
UrlInitialization Class
Utility functions used by rest of repo
Updating code for linter
Ignoring lint of complex functions:
check_and_post_network_port and check_and_post_network_port_network_port
Breaking up these functions may be a good idea in the future, but at this point is low priority. Similar lint warning should be assessed on a case-by-case basis.

Adding common code

---

.github/workflows/lint.yaml
filtering/check_glpi_computers.py
filtering/check_glpi_reservation.py
filtering/filter_computers.py
filtering/filter_reservations_by_project.py
filtering/requirements_example.yaml

Adding scripts for checking computers, reservations, filtering computers, and filtering reservations by project
Adding requirements example yaml
Ignoring E402 in the linter, required when appending the sys path as imports continue below
Ignoring complex function 'reservable' in linter

Adding filtering scripts, update workflow for sys path

---

common/urlinitialization.py
common/utils.py
population/create_glpi_computer_redfish.py

- Add BMC Address of computer to either a custom field or to the comments field in GLPI. If there is already a value in place, don't change it.

add bmc address to computers in glpi

---

common/utils.py
filtering/check_glpi_reservation.py

Allow users to get reservations from a specific hostname and/or user.

Add hostname and user options to check_glpi_reservation.py

---

common/utils.py
population/create_glpi_computer.py
population/create_glpi_computer_coreos.py
population/create_glpi_computer_redfish.py
population/update_switch_ports.py

Where possible, use `check_fields()` instead of duplicating code.

Replace repeated code with calls to check_fields()

---

population/create_glpi_computer_redfish.py

- Increase timeout from 5 to 20 secs
- Add more print statements to document what script is doing
- Handle edge cases where certain data can't be pulled from Sunbird

Handle edge cases and add more verbose print statements for rack workflow

---

population/create_glpi_computer_redfish.py

Set smart_storage_info to None and add check for it to avoid runtime errors

Account for cases where smart_storage can't be retrieved from HP machines

---

population/create_glpi_computer_redfish.py

- Handle cases when assets have moved rack locations. Now the location will automatically update in GLPI
- Some assets take up more than one RU - add code to handle this case.

Modify Rack Placements

---

README.md
common/urlinitialization.py
integration/ldap/compare_ldap_with_glpi.py
integration/ldap/general_ldap_example.yaml

This PR adds a script to sync GLPI groups with LDAP groups via a user-specified YAML file. A sample YAML file as well as documentation in the README  are provided.
There are a couple LDAP python packages, but they either require >100MB of dependencies or are not that actively maintained, so I opted to use subprocess -> ldapsearch for the time being.

Integrate ldap

---

Containerfile

Add a basic Containerfile to repo

---

common/utils.py
population/create_glpi_computer_redfish.py

Previously, items would not be updated because we weren't passing their ID into the PUT JSON. This PR fixes that, and rearranges the rack_item JSON so that the location of a machine in GLPI will be updated when its location changes in Sunbird.

Update items correctly

---

population/create_glpi_computer_redfish.py

`check_resp_redfish_api()` is unnecessary since redfish objects have a `status` attribute that accomplishes the same thing (I think we introduced redfish objects after writing `check_resp_redfish_api()` and never removed it).
This PR removes `check_resp_redfish_api()` and adjusts functions that call it.
Also use a context manager for Redfish tasks.

remove function and use context manager for redfish

---

population/create_glpi_computer_redfish.py

Helps with #66, similar to #72 
- Use .dict in get_network()
- Also remove json.loads() in post_to_glpi(), since it's no longer necessary (we're passing in a dict instead of json now)

remove .text from get_network()

---

population/create_glpi_computer_redfish.py
population/create_glpi_computer_redfish_wrapper.py

fix docstring for parse_list()

---

population/create_glpi_computer_redfish.py
population/create_glpi_computer_redfish_wrapper.py

Allow usage of SKU for machines that aren't Dell

---

filtering/filter_computers.py

Some functions in `filter_computers.py` were using `user_token` instead of `session`. Also remove `yaml.safe_load()`, the `computer` var is already a dictionary.

Fix incorrect variable

---

README.md
common/urlinitialization.py
common/utils.py
filtering/check_glpi_reservation.py
filtering/filter_computers.py
utilities/tag_unreservable_machines.py

- Add new CLI to tag unreservable machines
- move `check_computer_reservable()` to `utils.py`
- Add documentation to README

Tag unreservable machines

---

population/create_glpi_computer_redfish.py

Use `argpars.BooleanOptionalAction`. Now, `sku_for_dell` defaults to true if omitted, and adds an additional, more descriptive option to not use sku's for dell's (`--no-sku_for_dell`)

Update sku_for_dell option

---

population/create_glpi_computer_redfish.py

Rearrange code to make sure speed is always populated.

Make sure speed is populated when empty

---

utilities/update_accelerators.py

This script goes through every machine in GLPI and updates its accelerators.

Add script to update accelerators in GLPI
